
Applications:
  Gallery:                      # Output directory name.
    System: "org.gallery3d"     # System name of application.
    User:                       # User name of application.
      - DCIM
      - Pictures
      - Camera

  Telegram:
    System: "telegram.org"
    User: "Telegram"

  VK:
    System: "vk.org"
    User: "VK"